# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16d6ba28705ff44109f8b667980b8553e53c20f62b9e1dd4c8cb0af81d63f8032d982d0c6584d35ad869adda1546218546c95aa46f675ec07827cc6069c8367f

test:
  secret_key_base: 57a03a1ee41e0eee31c3a582e6d08e205c9e3e04229fed1a4fdc37a81a5992be771becf776561d669320ebacfc7193c5446443dfbbfdd772a5271bcfb75c5e21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
